language: ruby
rvm:
  - 1.9.3
  - 2.2.0
  - rbx-2
  - jruby-19mode

gemfile:
  - gemfiles/prawn-1.2.1.gemfile
  - gemfiles/prawn-1.3.0.gemfile
  - gemfiles/prawn-2.0.2.gemfile
  - gemfiles/prawn-master.gemfile

matrix:
  exclude:
    - rvm: 1.9.3
      gemfile: gemfiles/prawn-2.0.2.gemfile

    - rvm: jruby-19mode
      gemfile: gemfiles/prawn-2.0.2.gemfile


  allow_failures:
    - rvm: rbx-2
    - gemfile: gemfiles/prawn-master.gemfile
