language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.2
  - 2.2.0
  - rbx-2
  - jruby-19mode

gemfile:
  - gemfiles/prawn-1.1.0.gemfile
  - gemfiles/prawn-1.2.1.gemfile
  - gemfiles/prawn-1.3.0.gemfile
  - gemfiles/prawn-2.0.0.gemfile
  - gemfiles/prawn-master.gemfile

matrix:
  exclude:
    - rvm: 1.9.3
    gemfile: gemfiles/prawn-2.0.0.gemfile
    gemfile: gemfiles/prawn-master.gemfile

    - rvm: jruby-19mode
    gemfile: gemfiles/prawn-2.0.0.gemfile
    gemfile: gemfiles/prawn-master.gemfile

  allow_failures:
    - rvm: rbx-2
    - gemfiles/prawn-master.gemfile